#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 03, 2019 03:44:47 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import second_support

def vp_start_guin():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1m (root)
    second_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1m(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevelm(root)
    top = Toplevel1m(w)
    second_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1m():
    global w
    w.destroy()
    w = None

class Toplevel1m:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family {Segoe UI} -size 12 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font13 = "-family {Segoe UI Black} -size 13 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 20 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("864x619+194+65")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#e1cf79")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.023, rely=0.016, relheight=0.961
                , relwidth=0.446)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#a33a47")

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.208, rely=0.353,height=20, relwidth=0.556)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font=font13)
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Entry1_2 = tk.Entry(self.Frame1)
        self.Entry1_2.place(relx=0.156, rely=0.639,height=20, relwidth=0.66)
        self.Entry1_2.configure(background="white")
        self.Entry1_2.configure(disabledforeground="#a3a3a3")
        self.Entry1_2.configure(font=font13)
        self.Entry1_2.configure(foreground="#000000")
        self.Entry1_2.configure(highlightbackground="#d9d9d9")
        self.Entry1_2.configure(highlightcolor="black")
        self.Entry1_2.configure(insertbackground="black")
        self.Entry1_2.configure(selectbackground="#c4c4c4")
        self.Entry1_2.configure(selectforeground="black")

        self.Message1 = tk.Message(self.Frame1)
        self.Message1.place(relx=0.234, rely=0.218, relheight=0.123
                , relwidth=0.468)
        self.Message1.configure(background="#a33a47")
        self.Message1.configure(font=font9)
        self.Message1.configure(foreground="#ffffff")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''* Name :''')
        self.Message1.configure(width=180)

        self.Message2 = tk.Message(self.Frame1)
        self.Message2.place(relx=0.182, rely=0.941, relheight=0.022
                , relwidth=0.571)
        self.Message2.configure(background="#a33a47")
        self.Message2.configure(font=font10)
        self.Message2.configure(foreground="#ffffff")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(text='''* => optional''')
        self.Message2.configure(width=220)

        self.Message1_7 = tk.Message(self.Frame1)
        self.Message1_7.place(relx=0.208, rely=0.471, relheight=0.156
                , relwidth=0.571)
        self.Message1_7.configure(background="#a33a47")
        self.Message1_7.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.Message1_7.configure(foreground="#ffffff")
        self.Message1_7.configure(highlightbackground="#d9d9d9")
        self.Message1_7.configure(highlightcolor="black")
        self.Message1_7.configure(text='''* Email :''')
        self.Message1_7.configure(width=220)

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.544, rely=0.016, relheight=0.961
                , relwidth=0.434)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#a33a47")

        self.Button1_6 = tk.Button(self.Frame2)
        self.Button1_6.place(relx=0.32, rely=0.756, height=44, width=157)
        self.Button1_6.configure(activebackground="#ececec")
        self.Button1_6.configure(activeforeground="#ffffff")
        self.Button1_6.configure(background="#a33a47")
        self.Button1_6.configure(borderwidth="5")
        self.Button1_6.configure(cursor="boat")
        self.Button1_6.configure(disabledforeground="#a3a3a3")
        self.Button1_6.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.Button1_6.configure(foreground="#ffffff")
        self.Button1_6.configure(highlightbackground="#d9d9d9")
        self.Button1_6.configure(highlightcolor="black")
        self.Button1_6.configure(pady="0")
        self.Button1_6.configure(text='''Proceed''')

        self.Entry2 = tk.Entry(self.Frame2)
        self.Entry2.place(relx=0.213, rely=0.538,height=20, relwidth=0.571)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font=font12)
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.Message1_8 = tk.Message(self.Frame2)
        self.Message1_8.place(relx=0.187, rely=0.319, relheight=0.173
                , relwidth=0.613)
        self.Message1_8.configure(background="#a33a47")
        self.Message1_8.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.Message1_8.configure(foreground="#ffffff")
        self.Message1_8.configure(highlightbackground="#d9d9d9")
        self.Message1_8.configure(highlightcolor="black")
        self.Message1_8.configure(text='''Travel Destination :''')
        self.Message1_8.configure(width=230)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(font="{Segoe UI} 9")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_guin()





